cradle:
  cabal:
    - path: "./app/Main.hs"
      component: "GLaDOS2023:exe:glados"

    - path: "./test"
      component: "GLaDOS2023:test:test"

    - path: "./app"
      component: "GLaDOS2023:test:test"
